stages:
  - pre-test
  - test
  - build

build-test-image:
  stage: pre-test
  script:
    - cd admin/ci/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_SLUG || true
    - docker build --file Dockerfile.tests --tag $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_SLUG --cache-from $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_SLUG
  services:
    - docker:dind

test:
  image: $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_SLUG
  stage: test
  services:
    - redis
    - name: quay.io/acoustid/postgresql:master
      alias: postgres
    - name: quay.io/acoustid/acoustid-index:2018.01.13
      alias: acoustid-index
  variables:
    POSTGRES_USER: acoustid
    POSTGRES_PASSWORD: acoustid
    POSTGRES_DB: acoustid_test
    ACOUSTID_TEST_DATABASE_APP_HOST: localhost
    ACOUSTID_TEST_DATABASE_APP_RO_HOST: localhost
    ACOUSTID_TEST_DATABASE_FINGERPRINT_HOST: localhost
    ACOUSTID_TEST_DATABASE_FINGERPRINT_RO_HOST: localhost
    ACOUSTID_TEST_DATABASE_INGEST_HOST: localhost
    ACOUSTID_TEST_DATABASE_INGEST_RO_HOST: localhost
    ACOUSTID_TEST_DATABASE_MUSICBRAINZ_HOST: localhost
    ACOUSTID_TEST_DATABASE_MUSICBRAINZ_RO_HOST: localhost
    ACOUSTID_TEST_REDIS_HOST: localhost
    ACOUSTID_TEST_INDEX_HOST: localhost
  cache:
    key: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG
    paths:
      - pip-cache/
  script:
    - set
    - ./admin/ci/run-tests.sh

build:
  stage: build
  script:
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
    - ./admin/ci/build-image.sh
  services:
    - docker:dind
