stages:
  - pre-test
  - test
  - build

services:
  - redis
  - name: quay.io/acoustid/postgresql:master
    alias: postgres

variables:
  POSTGRES_USER: acoustid
  POSTGRES_PASSWORD: acoustid
  POSTGRES_DB: acoustid_test
  ACOUSTID_TEST_POSTGRES_HOST: postgres
  ACOUSTID_TEST_REDIS_HOST: redis

build-test-image:
  stage: pre-test
  script:
    - cd admin/ci/
    - docker build -f Dockerfile.tests -t $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_NAME .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_NAME
  tags:
    - docker

test:
  image: $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_NAME
  stage: test
  script:
    - ./admin/ci/run-tests.sh
  tags:
    - docker

build:
  stage: build
  script:
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
    - ./admin/ci/build-image.sh
  tags:
    - docker
