stages:
  - test
  - build

test:
  stage: test
  script:
    - ./admin/ci/run-all.sh
  tags:
    - docker

build:
  stage: build
  script:
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
    - ./admin/ci/build-image.sh
  tags:
    - docker
