services:
  - docker:dind

stages:
  - build

before_script:
  - docker info

build:
  stage: build
  script:
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
    - ./ci/build-image.sh
  tags:
    - docker
