stages:
  - pre-test
  - test
  - build

build-docker-compose:
  stage: pre-test
  script:
    - cd admin/ci/
    - docker build -f Dockerfile.docker -t quay.io/acoustid/docker-compose:stable .
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
    - docker push quay.io/acoustid/docker-compose:stable
  tags:
    - docker

test:
  image: quay.io/acoustid/docker-compose:stable
  stage: test
  script:
    - ./admin/ci/run-all.sh
  tags:
    - docker

build:
  stage: build
  script:
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
    - ./admin/ci/build-image.sh
  tags:
    - docker
