name: Build and test

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ '2.x', '3.x' ]

    services:
      postgresql:
        image: quay.io/acoustid/postgresql:master
        ports:
          - 5432/tcp
        env:
          POSTGRES_USER: acoustid
          POSTGRES_PASSWORD: acoustid
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379/tcp
      index:
        image: quay.io/acoustid/acoustid-index:2018.01.13
        ports:
          - 6080/tcp

    steps:

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install additional requirements
        run: |
          pip install tox
          sudo apt-get update
          sudo apt-get install libchromaprint1

      - name: Setup database
        run: |
          container=$(docker ps -q -f expose=5432)
          docker exec -i -e PGUSER=$PGUSER -e PGPASSWORD=$PGPASSWORD -e PGDATABASE=$PGDATABASE $container psql < ./admin/ci/create_db.sql
        env:
          PGUSER: acoustid
          PGPASSWORD: acoustid
          PGDATABASE: postgres

      - name: Run tests
        run: |
          sed -i 's/psycopg2/psycopg2-binary/' requirements_py2.txt
          sed -i 's/psycopg2/psycopg2-binary/' requirements_py3.txt
          tox
        env:
          ACOUSTID_TEST_DATABASE_APP_HOST: localhost
          ACOUSTID_TEST_DATABASE_APP_PORT: ${{ job.services.postgresql.ports['5432'] }}
          ACOUSTID_TEST_DATABASE_APP_RO_HOST: localhost
          ACOUSTID_TEST_DATABASE_APP_RO_PORT: ${{ job.services.postgresql.ports['5432'] }}
          ACOUSTID_TEST_DATABASE_FINGERPRINT_HOST: localhost
          ACOUSTID_TEST_DATABASE_FINGERPRINT_PORT: ${{ job.services.postgresql.ports['5432'] }}
          ACOUSTID_TEST_DATABASE_FINGERPRINT_RO_HOST: localhost
          ACOUSTID_TEST_DATABASE_FINGERPRINT_RO_PORT: ${{ job.services.postgresql.ports['5432'] }}
          ACOUSTID_TEST_DATABASE_INGEST_HOST: localhost
          ACOUSTID_TEST_DATABASE_INGEST_PORT: ${{ job.services.postgresql.ports['5432'] }}
          ACOUSTID_TEST_DATABASE_INGEST_RO_HOST: localhost
          ACOUSTID_TEST_DATABASE_INGEST_RO_PORT: ${{ job.services.postgresql.ports['5432'] }}
          ACOUSTID_TEST_DATABASE_MUSICBRAINZ_HOST: localhost
          ACOUSTID_TEST_DATABASE_MUSICBRAINZ_PORT: ${{ job.services.postgresql.ports['5432'] }}
          ACOUSTID_TEST_DATABASE_MUSICBRAINZ_RO_HOST: localhost
          ACOUSTID_TEST_DATABASE_MUSICBRAINZ_RO_PORT: ${{ job.services.postgresql.ports['5432'] }}
          ACOUSTID_TEST_REDIS_HOST: localhost
          ACOUSTID_TEST_REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
          ACOUSTID_TEST_INDEX_HOST: localhost
          ACOUSTID_TEST_INDEX_PORT: ${{ job.services.index.ports['6080'] }}
